language: go

go:
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - tip

os:
  - linux

services:
  - docker

branches:
  only:
  - master
  - develop

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

jobs:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.4/hadolint-Linux-x86_64
  - chmod +x perfecto-docker
  - chmod +x hadolint
  - ./hadolint --version
  - make deps

script:
  - make all
  - .travis/script.sh
  - ./perfecto-docker common/yo.spec
  - ./hadolint Dockerfile
